import type { LoreType } from '@domain/entities/lore'

export const loreTypeLabels: Record<LoreType, string> = {
  artifact: 'Artefacto',
  person: 'Personaje',
  zone: 'Zona',
  creature: 'Criatura',
  ethnicity: 'Etnia',
  event: 'Evento',
  myth: 'Mito',
  organization: 'Organización',
}

export const loreFieldTemplates: Record<LoreType, string[]> = {
  artifact: ['Descripción', 'Historia', 'Origen', 'Tipo', 'Estado', 'Portador actual', 'Valor narrativo', 'Conexiones', 'Pistas', 'Uso en mesa'],
  person: [
    'Descripción',
    'Historia',
    'Motivaciones',
    'Rol en campaña',
    'Facción',
    'Ubicación',
    'Alignment',
    'Estado',
    'Relación con players',
    'Pistas',
    'Uso en mesa',
  ],
  zone: ['Descripción', 'Historia', 'Tipo de zona', 'Ubicación', 'Control', 'Amenaza', 'Acceso', 'Claves', 'Encuentros', 'Conexiones', 'Pistas', 'Uso en mesa'],
  creature: ['Descripción', 'Historia', 'Tipo', 'Facción', 'Ubicación', 'Amenaza', 'Estado', 'Comportamiento', 'Habilidades', 'Pistas', 'Uso en mesa'],
  ethnicity: ['Descripción', 'Historia', 'Cultura', 'Territorio', 'Relaciones', 'Tensiones', 'Pistas', 'Uso en mesa'],
  event: [
    'Descripción',
    'Historia',
    'Época',
    'Lugar',
    'Facciones implicadas',
    'Estado',
    'Importancia',
    'Consecuencias',
    'Pistas',
    'Conexiones',
    'Uso en mesa',
  ],
  myth: ['Descripción', 'Historia', 'Moral', 'Significado cultural', 'Variantes', 'Pistas', 'Uso en mesa'],
  organization: [
    'Ideología',
    'Descripción',
    'Historia',
    'Número de miembros',
    'Alignment',
    'Liderazgo',
    'Base',
    'Alcance',
    'Métodos',
    'Recursos',
    'Aliados',
    'Enemigos',
    'Estado actual',
    'Señales visibles',
    'Uso en mesa',
  ],
}

export const loreCompactFieldNames = [
  'Tipo',
  'Tipo de zona',
  'Estado',
  'Portador actual',
  'Valor narrativo',
  'Rol en campaña',
  'Facción',
  'Ubicación',
  'Alignment',
  'Relación con players',
  'Número de miembros',
  'Liderazgo',
  'Base',
  'Alcance',
  'Recursos',
  'Aliados',
  'Enemigos',
  'Estado actual',
  'Señales visibles',
  'Control',
  'Amenaza',
  'Acceso',
  'Época',
  'Lugar',
  'Facciones implicadas',
  'Territorio',
  'Relaciones',
  'Tensiones',
  'Conexiones',
  'Pistas',
]

export const loreLongFieldNames = [
  'Ideología',
  'Descripción',
  'Historia',
  'Motivaciones',
  'Origen',
  'Métodos',
  'Claves',
  'Encuentros',
  'Comportamiento',
  'Habilidades',
  'Cultura',
  'Importancia',
  'Significado',
  'Consecuencias',
  'Moral',
  'Significado cultural',
  'Variantes',
  'Uso en mesa',
]

export const loreFieldDisplayOrder = [
  'Ideología',
  'Descripción',
  'Historia',
  'Motivaciones',
  'Origen',
  'Métodos',
  'Comportamiento',
  'Habilidades',
  'Cultura',
  'Importancia',
  'Significado',
  'Consecuencias',
  'Moral',
  'Significado cultural',
  'Variantes',
  'Uso en mesa',
  'Tipo',
  'Tipo de zona',
  'Rol en campaña',
  'Facción',
  'Ubicación',
  'Control',
  'Amenaza',
  'Acceso',
  'Época',
  'Lugar',
  'Facciones implicadas',
  'Portador actual',
  'Valor narrativo',
  'Número de miembros',
  'Alignment',
  'Liderazgo',
  'Base',
  'Alcance',
  'Recursos',
  'Aliados',
  'Enemigos',
  'Estado actual',
  'Señales visibles',
  'Estado',
  'Relación con players',
  'Territorio',
  'Relaciones',
  'Tensiones',
  'Conexiones',
  'Pistas',
]
