import type { LoreType } from '@domain/entities/lore'

export const loreTypeLabels: Record<LoreType, string> = {
  artifact: 'Artefacto',
  person: 'Personaje',
  zone: 'Zona',
  creature: 'Criatura',
  ethnicity: 'Etnia',
  event: 'Evento',
  myth: 'Mito',
  organization: 'Organización',
}

export const loreFieldTemplates: Record<LoreType, string[]> = {
  artifact: ['Descripción', 'Origen', 'Historia', 'Uso en mesa'],
  person: [
    'Descripción',
    'Historia',
    'Motivaciones',
    'Rol en campaña',
    'Facción',
    'Ubicación',
    'Alignment',
    'Estado',
    'Relación con players',
    'Pistas',
    'Uso en mesa',
  ],
  zone: ['Descripción', 'Historia', 'Claves', 'Encuentros', 'Conexiones', 'Uso en mesa'],
  creature: ['Descripción', 'Comportamiento', 'Habilidades', 'Señales', 'Uso en mesa'],
  ethnicity: ['Descripción', 'Cultura', 'Historia', 'Relaciones', 'Uso en mesa'],
  event: ['Descripción', 'Significado', 'Consecuencias', 'Pistas', 'Uso en mesa'],
  myth: ['Historia', 'Moral', 'Significado cultural', 'Variantes', 'Uso en mesa'],
  organization: [
    'Ideología',
    'Descripción',
    'Historia',
    'Número de miembros',
    'Alignment',
    'Liderazgo',
    'Base',
    'Alcance',
    'Métodos',
    'Recursos',
    'Aliados',
    'Enemigos',
    'Estado actual',
    'Señales visibles',
    'Uso en mesa',
  ],
}
